accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # /accounts/
    path('', views.index, name='index'),

    # /accounts/a123/
    path('a<int:account_id>/', views.account, name='account'),

    # /accounts/a123/l123
    path('a<int:account_id>/l<int:list_id>/', views.list, name='list'),

    # /accounts/a123/lists
    path('a<int:account_id>/lists/', views.lists, name='lists'),

    # /accounts/a123/l123/i123
    path('a<int:account_id>/l<int:list_id>/i<int:item_id>/', views.item, name='item'),

    # /accounts/a123/l123/prioritized
    path('a<int:account_id>/l<int:list_id>/prioritized/', views.prioritized, name='prioritized'),
]

homebudget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models


class Account(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    monthly_budget = models.DecimalField(max_digits=10, decimal_places=2)
    month_expenses = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.last_name + ' - ' + str(self.monthly_budget)


class List(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=5000, default=None)
    total_sum = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.name + ' - ' + str(self.total_sum)


class Item(models.Model):
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(max_length=5000, default=None)
    is_prioritized = models.BooleanField(default=False)

    def __str__(self):
        return self.name + ' - ' + str(self.price)

accounts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Account, List, Item


def index(request):
    return render(request, 'accounts/index.html', {'all_accounts': Account.objects.all()})


def account(request, account_id):
    return render(request, 'accounts/account.html', {
        'account': get_object_or_404(Account, id=account_id)
    })


def list(request, account_id, list_id):
    return render(request, 'accounts/list.html', {
        'account': get_object_or_404(Account, id=account_id),
        'list': get_object_or_404(List, id=list_id)
    })


def lists(request, account_id):
    return render(request, 'accounts/lists.html', {
        'account': get_object_or_404(Account, id=account_id),
        'lists': List.objects.filter(account=account_id)})


def item(request, account_id, list_id, item_id):
    return render(request, 'accounts/item.html', {
        'account': get_object_or_404(Account, id=account_id),
        'item': get_object_or_404(Item, id=item_id)
    })


def prioritized(request, account_id, list_id):
    list = get_object_or_404(List, id=list_id)
    try:
        selected_item = list.item_set.get(id=request.POST['item'])
    except (KeyError, Item.DoesNotExist):
        return render(request, 'accounts/list.html', {
            'account': get_object_or_404(Account, id=account_id),
            'list': list,
            'error_message': 'You did not select any valid item'
        })
    else:
        selected_item.is_prioritized = True
        selected_item.save()
        return render(request, 'accounts/list.html', {
            'account': get_object_or_404(Account, id=account_id),
            'list': list
        })

accounts/templates/accounts/account.html
{% extends 'accounts/base.html' %}

{% block body %}
    <h1>{{account.first_name}} {{account.last_name}}</h1>
    <h2>Monthly Budget: {{account.monthly_budget}}</h2>

    <ul>
        {% for list in account.list_set.all %}
            <li><a href="{% url 'accounts:list' account.id list.id %}">{{list.name}}</a> - {{list.total_sum}} {{list.description}}</li>
        {% endfor%}
    </ul>

    <h2>Total Expenses: {{account.month_expenses}}</h2>
{% endblock %}

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Budget</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-info navbar-dark">
        <div class="container-fluid">

            <!--Header-->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'accounts:index' %}">Home Budget</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#topNavBar">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <!--Items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'accounts:lists' account.id %}">
                            <i class="fa fa-list-ul fa-lg"></i>&nbsp; Lists
                        </a>
                    </li>
                </ul>
            </div>

            <!--Logout-->
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item active">
                    <a class="nav-link" href="#">
                        <i class="fa fa-sign-out fa-lg"></i>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</body>
{% block body %}
{% endblock %}
</html>

accounts/templates/accounts/index.html
{% if all_accounts %}
    <h3>Here are all the accounts</h3>
    <ul>
        {% for account in all_accounts%}
            <li><a href="{% url 'accounts:account' account.id %}">{{account.first_name}} {{account.last_name}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>No accounts created</h3>
{% endif %}

accounts/templates/accounts/item.html
{% extends 'accounts/base.html' %}

{% block body %}
    <h1>Item: {{item.name}}</h1>
    <h1>Price: {{item.price}}</h1>
    <h2>Description: {{item.description}}</h2>
{% endblock %}

accounts/templates/accounts/list.html
{% extends 'accounts/base.html' %}

{% block body %}
    <h1>{{list.name}}</h1>
    <h2>{{list.total_sum}}</h2>

    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}

    <ul>
        {% for item in list.item_set.all %}
            <li><a href="{% url 'accounts:item' list.account.id list.id item.id %}">{{item.name}}</a> - {{item.price}}</li>
        {% endfor%}
    </ul>

    <form action="{% url 'accounts:prioritized' list.account.id list.id %}" method="post">
        {% csrf_token %}
        {% for item in list.item_set.all %}
            <input type="radio" id="item{{forloop.counter}}" name="item" value="{{item.id}}"/>
            <label for="item{{forloop.counter}}">
                {{item.name}}
                {% if item.is_prioritized %}
                    <img src="http://i.imgur.com/b9b13Rd.png"/>
                {% endif %}
            </label><br>
        {% endfor %}
        <input type="submit" value="Prioritized"/>
    </form>
{% endblock %}

accounts/templates/accounts/lists.html
{% extends 'accounts/base.html' %}

{% block body %}
    <ul>
        {% for list in lists %}
            <li><a href="{% url 'accounts:list' list.account.id list.id %}">{{list.name}}</a> - {{list.total_sum}} {{list.description}}</li>
        {% endfor %}
    </ul>
{% endblock %}